### ISSUE TITLE
window size and place not kept between every use

### ISSUE THREAD

**Issue by Altoholic** [casperstorm/ajour#488] opened 2021-01-13 22:28 UTC
**Describe the bug**
Very minor bug: the position and size of the window is never kept between every use of Ajour.

**To Reproduce**
1. open Ajour
2. modify size or/and position of the main window
3. close Ajour
4. open it again: size and position of the window are not kept

**Expected behavior**
The window should stay where i put it previously, at the size i choose.

**Software involved**

 - OS: Windows 10
 - Ajour version: 0.6.1
 - Classic WoW

**Comment by tarkah** [comment] 2021-01-14 00:17
duplicate of #269

This is an upstream issue and something we can't implement currently unfortunately.

**Closed by tarkah** 2021-01-14 00:17 UTC
Labels: B - bug
