### ISSUE TITLE
Multiple addons not showing up

### ISSUE THREAD

**Issue by mawmaw1** [casperstorm/ajour#105] opened 2020-09-13 08:50 UTC
Addons does not show up in Ajour, but is recognized and updateable in twitch app:

https://www.curseforge.com/wow/addons/extended-character-stats
https://www.curseforge.com/wow/addons/bagnon
https://www.curseforge.com/wow/addons/weaponswingtimer

**Comment by mlablah** [comment] 2020-09-13 10:13
Hello @mawmaw1. Thank you for trying out Ajour. We really appreciate it. 👍 

Just writing to get some additional context and add some of my own.

Can you confirm that you are using the latest release version of the client (0.3.2)?

Also can you confirm that you specified the "flavor" of the game you are using in the settings?

I have tried to reproduce the error by downloading the latest retail and classic version of the addons but get a different result from you.

Bagnon and Weaponswingtimer have retail versions and both show up in Ajour:
![image](https://user-images.githubusercontent.com/68285419/93015337-edc32c00-f5b8-11ea-84c9-93aa762f32df.png)

I then switched to classic flavor, deleted this file: %appdata%\ajour\fingerprints.yml to make Ajour forgot about the retail version of the addons, and restarted the app.

I then see only bagnon:
![image](https://user-images.githubusercontent.com/68285419/93015377-3844a880-f5b9-11ea-87c9-7dece4b1280a.png)

We are looking into why the classic versions of WeaponSwingMaster and ExtendedCharacterStats are not shown. We suspect it's due to their title in the toc.

**Comment by mawmaw1** [comment] 2020-09-13 10:18
Thanks for a great program btw!

I confirm using 0.3.2 and have selected the classic flavor.

**Comment by casperstorm** [comment] 2020-09-13 10:25
I am working on a fix, for now this executable should fix your problem:
[ajour.zip](https://github.com/casperstorm/ajour/files/5213919/ajour.zip)

Let me know if it works.

**Comment by mawmaw1** [comment] 2020-09-13 10:33
Wow that was quick, thanks! It found the 2 addons mentioned by @mlablah - Bagnon still isn't found for some reason.

The program crashed, and I got the following message trying to open it again: "Operation did not complete successfully because the file contains a virus or potentially unwanted software".

And my desktop then became unresponsive and I had to restart my computer 🤣

**Comment by casperstorm** [comment] 2020-09-13 10:58
> It found the 2 addons mentioned by @mlablah

Great, issue was that our logic for parsing them failed, but it is now fixed in #106. It will be released early next week.

> Bagnon still isn't found for some reason.

I think the reason is that the content may have been locally modified. You could try to delete the addon from `Interface/AddOns` (BagBrother, Bagnon, Bagnon_Config, Bagnon_GuildBank and  Bagnon_VoidStorage) and re-download the addon. I can see all three addons now (running #106).

<img width="788" alt="Screenshot 2020-09-13 at 12 56 38" src="https://user-images.githubusercontent.com/2248455/93016333-b22c6000-f5c0-11ea-96d5-d1eefd396210.png">

> The program crashed, and I got the following message trying to open it again: "Operation did not complete successfully because the file contains a virus or potentially unwanted software".

Ough 😩 That sucks. I don't know why Defender would flag Ajour.

**Closed** 2020-09-13 11:04 UTC
Labels: type: bug

**Comment by casperstorm** [comment] 2020-09-13 11:05
Closing this now @mawmaw1 – a new release will be out soon which will include the fix. Thanks for reporting and helping us make Ajour better.
