### ISSUE TITLE
Catalog stuck at loading...

### ISSUE THREAD

**Issue by Qahlel** [casperstorm/ajour#369] opened 2020-11-20 02:17 UTC
**Describe the bug**
Catalog doesn't show any addons for me to install. Instead I get the following error message at top: EOF while parsing an object at line 1 column 869971.

**Screenshots**
https://dl.dropboxusercontent.com/s/fgdykngfzf6gam8/ajour-opengl_201120-051625-1920x1040.png

**Software involved**
Please complete the following information:
 - OS: Widnwos 10
 - Ajour version: 0.5.1

**Log Output**
05:11:50.859 [ajour][INFO] Ajour 0.5.1 has started.
05:11:50.861 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "C:\\World of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        ignored: {
            Retail: [],
        },
        release_channels: {
            Retail: {
                "Ace3": Stable,
                "ImprovedLootFrame": Stable,
                "Overachiever": Stable,
            },
        },
    },
    theme: Some(
        "Light",
    ),
    column_config: V3 {
        my_addons_columns: [
            ColumnConfigV2 {
                key: "title",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "local",
                width: Some(
                    237,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "remote",
                width: Some(
                    244,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "status",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "channel",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "author",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    110,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "date_released",
                width: Some(
                    110,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "source",
                width: Some(
                    110,
                ),
                hidden: false,
            },
        ],
        catalog_columns: [
            ColumnConfigV2 {
                key: "addon",
                width: Some(
                    150,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "description",
                width: Some(
                    804,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "source",
                width: Some(
                    70,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "num_downloads",
                width: Some(
                    105,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    105,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "date_released",
                width: Some(
                    105,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "install",
                width: Some(
                    85,
                ),
                hidden: false,
            },
        ],
    },
    window_size: Some(
        (
            1919,
            1016,
        ),
    ),
    scale: Some(
        1.4000000000000004,
    ),
    backup_directory: None,
    backup_addons: false,
    backup_wtf: false,
}
05:11:50.861 [ajour::gui][DEBUG] antialiasing: false
05:11:50.874 [ajour_core::theme][DEBUG] loading user themes
05:11:50.874 [ajour_core::utility][DEBUG] checking for application update
05:11:50.875 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
05:11:51.131 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
05:11:51.131 [ajour::gui::update][DEBUG] Message::CachesLoaded(error: false)
05:11:51.133 [ajour::gui::update][DEBUG] Message::Parse
05:11:51.133 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\World of Warcraft\\_retail_\\Interface/AddOns"
05:11:51.133 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\World of Warcraft\\_ptr_\\Interface/AddOns"
05:11:51.134 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\World of Warcraft\\_beta_\\Interface/AddOns"
05:11:51.134 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\World of Warcraft\\_classic_\\Interface/AddOns"
05:11:51.134 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\World of Warcraft\\_classic_ptr_\\Interface/AddOns"
05:11:51.135 [ajour_core::parse][DEBUG] Retail - parsing addons folder
05:11:51.135 [ajour_core::parse][DEBUG] Retail PTR - parsing addons folder
05:11:51.135 [ajour_core::parse][DEBUG] Retail Beta - parsing addons folder
05:11:51.135 [ajour_core::parse][DEBUG] Classic - parsing addons folder
05:11:51.135 [ajour_core::parse][DEBUG] Classic PTR - parsing addons folder
05:11:51.135 [ajour_core::parse][DEBUG] Retail - 159 folders in AddOns directory to parse
05:11:51.137 [ajour_core::parse][DEBUG] Retail - 159 fingerprints: 159 cached, 0 calculated, 0 added, 0 removed
05:11:51.155 [ajour_core::parse][DEBUG] Retail - 159 addon folders successfully parsed from '.toc'
05:11:51.155 [ajour_core::parse][DEBUG] Retail - 0 cached entries
05:11:51.155 [ajour_core::parse][DEBUG] Retail - 159 unique fingerprints to check against curse api
05:11:51.205 [ajour::gui::update][ERROR] Message::ParsedAddons(Retail PTR) - Addon directory not found: "C:\\World of Warcraft\\_ptr_\\Interface/AddOns"
05:11:51.205 [ajour::gui::update][ERROR] Message::ParsedAddons(Retail Beta) - Addon directory not found: "C:\\World of Warcraft\\_beta_\\Interface/AddOns"
05:11:51.205 [ajour::gui::update][ERROR] Message::ParsedAddons(Classic) - Addon directory not found: "C:\\World of Warcraft\\_classic_\\Interface/AddOns"
05:11:51.205 [ajour::gui::update][ERROR] Message::ParsedAddons(Classic PTR) - Addon directory not found: "C:\\World of Warcraft\\_classic_ptr_\\Interface/AddOns"
05:11:51.301 [ajour::gui::update][DEBUG] Message::LatestRelease(Some("0.5.1"))
05:11:54.313 [ajour_core::parse][DEBUG] Retail - 107 curse packages fetched
05:11:54.313 [ajour_core::parse][DEBUG] Retail - 0 tukui packages fetched
05:11:54.974 [ajour_core::parse][DEBUG] Retail - 22 wowi packages fetched
05:11:54.974 [ajour_core::parse][DEBUG] Retail - 0 git packages fetched
05:11:54.975 [ajour_core::parse][DEBUG] Retail - 107 addons built from curse packages
05:11:54.975 [ajour_core::parse][DEBUG] Retail - 0 addons built from tukui packages
05:11:54.975 [ajour_core::parse][DEBUG] Retail - 0 addons built from wowi packages
05:11:54.975 [ajour_core::parse][DEBUG] Retail - 0 addons built from git packages
05:11:54.975 [ajour_core::parse][DEBUG] Retail - 1 unknown addon folders
05:11:54.976 [ajour_core::parse][DEBUG] Retail - 108 addons successfully parsed
05:11:54.978 [ajour::gui::update][DEBUG] Message::ParsedAddons(Retail, 108 addons)
05:11:57.680 [ajour::gui::update][DEBUG] Interaction::ModeSelected(Catalog)
05:12:20.948 [ajour::gui::update][ERROR] EOF while parsing an object at line 1 column 869971
05:13:35.937 [ajour::gui::update][DEBUG] Interaction::Settings
05:13:40.141 [ajour::gui::update][DEBUG] Interaction::Settings

**Comment by casperstorm** [comment] 2020-11-20 12:01
Duplicate of #357.
This will be fixed in next version.

**Closed by casperstorm** 2020-11-20 12:01 UTC
Labels: B - bug, F - duplicate
