### ISSUE TITLE
Mac Version Display Hard to Read

### ISSUE THREAD

**Issue by Brightbrown** [casperstorm/ajour#201] opened 2020-10-05 23:00 UTC
**Describe the bug**
Dark Theme impossible to read text, text too faint, "Light" better but still not right

**Screenshots**
<a href="https://imgur.com/BOfzTTy"><img src="https://i.imgur.com/BOfzTTy.jpg" title="source: imgur.com" /></a>

**Software involved**
 - OS: MacOS 10.12.6
 - Ajour version: 0.3.5

**Log Output**
Display only issue

**Comment by casperstorm** [comment] 2020-10-06 06:44
There is clearly a issue with Ajour on your macOS, @Brightbrown. This we have also discussed on our [Discord](https://discord.gg/4838t9R). I still cant reproduce this problem where colors are off, but could it have something to do with you fiddling with `ColorSync.framework`?

Anyway, you could make your own theme for Ajour and see if you can hit some color combinations which works better for your macOS: [Installing custom themes](https://github.com/casperstorm/ajour/blob/master/THEMES.md).

I'll close this issue now. Feel free to reopen if anyone else run into this problem.

**Closed by casperstorm** 2020-10-06 06:44 UTC
Labels: type: bug

**Comment by Brightbrown** [comment] 2020-10-06 14:01
Actually, I didn’t fool with my ColorSync as you linked an image showing the compiler built it for 10.11 and up. The app does “react” to Light & Dark under themes.

Happy to try custom themes, but the examples on the page you linked me to only have png graphic files, but it says it meeds a xxx.yml file. Can I get the yml files for any of those examples… or exactly how do I create one?

**Comment by casperstorm** [comment] 2020-10-06 14:07
Easiest would be to open `Terminal.app` and write:
```
touch ~/.config/ajour/themes/brightbrown.yml
open ~/.config/ajour/themes
```

Now you should see a Finder window with a file called `brightbrown.yml`. Open this with a text editor of choice and fill it out with the following:

```
name: Brightbrown
palette:
  primary: '#67ac85'
  secondary: '#7fabbd'
  surface: '#222226'
  on_surface: '#aaaaaa'
  background: '#202022'
  error: '#ec7060'
```

Edit the above hex colors as you like.
