### ISSUE TITLE
Update without erasing changes

### ISSUE THREAD

**Issue by Akkuma** [casperstorm/ajour#352] opened 2020-11-12 17:16 UTC
**Is your feature request related to a problem? Please describe.**
Using Plater, I've added media locally to the addon. However, when I update it the added media is erased and requires me to manually download it again.

**Describe the solution you'd like**
A way to keep custom files when the addon updates. This might be a way to flag certain files as custom, to add back or a way to overwrite without first deleting or even manually deleting each individual file from the original addon as to preserve the custom files.

**Describe alternatives you've considered**
The only alternative would be to manually download the addon and copy/paste it as to prevent initial deletion or have a script to copy the files and then add them back.

**Comment by casperstorm** [comment] 2020-11-18 12:03
This is out of scope for now.
If you want to have modified addons in Ajour I recommend you ignore them by pressing details and then "Ignore". Then you can still keep pressing "Update all" and avoid having Plater replaced with a new version.

**Closed** 2020-11-18 12:04 UTC
Labels: B - missing feature, F - wontfix, S - addons

**Comment by Akkuma** [comment] 2020-11-18 14:25
As an fyi, this isn't an unexpected usage of something like Plater, but there aren't other addons I can think of that you generally do this in as well.

**Comment by casperstorm** [comment] 2020-11-18 16:33
@Akkuma Completely understand that. The problem is that we take a hash of the folder content of an addon which we use to match against the api. If you modify the content we can't match it.
