### ISSUE TITLE
WeakAuras not loading/missing auras

### ISSUE THREAD

**Issue by Maglore85** [casperstorm/ajour#466] opened 2021-01-04 17:24 UTC
Hello !

First off, I wanted to thank you for the software. It is really well done and I think everyone really appreciate it.

I simply want to help you get the software fully working. This is not a critical issue since I can press refresh to reload the list again. But for a person that would have 20-30 auras, it may be problematic for sure.

**Describe the bug**
Sometimes, the WeakAuras list is missing auras or do not load.

**To Reproduce**
1. Go to 'My WeakAuras'
2. Click on 'Refresh'

**Expected behavior**
Always show the full list (not just a partial list) of the configured auras.

**Screenshots**
See video attached. Also, the video do not show the Discipline/Holy priest aura.
https://user-images.githubusercontent.com/23324894/103560000-0e273700-4e85-11eb-96fc-67ff65db3fad.mp4

**Software involved**
Please complete the following information:
 - OS: Windows 10 Pro Version 20H2 build 19042.685
 - Ajour version: 0.6.1
 - WeakAuras: Warrior: https://wago.io/Afenar_Warrior - Mage: https://wago.io/Afenar_Mage - Shadow: https://wago.io/Afenar_Shadow - Holy & Discipline: https://wago.io/Holy&DC_AfenarUI

**Additional context**

**Log Output**
```
11:56:56.509 [ajour][INFO] Ajour 0.6.1 has started.
11:56:56.510 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: Some(
            "D:\\World of Warcraft",
        ),
        flavor: Retail,
    },
    addons: Addons {
        global_release_channel: Stable,
        ignored: {
            Retail: [],
        },
        release_channels: {
            Retail: {},
        },
        delete_saved_variables: false,
    },
    theme: None,
    column_config: V3 {
        my_addons_columns: [
            ColumnConfigV2 {
                key: "title",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "local",
                width: Some(
                    291,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "remote",
                width: Some(
                    196,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "status",
                width: Some(
                    186,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "channel",
                width: Some(
                    85,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "author",
                width: Some(
                    85,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    110,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "date_released",
                width: Some(
                    110,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "source",
                width: Some(
                    110,
                ),
                hidden: false,
            },
        ],
        catalog_columns: [
            ColumnConfigV2 {
                key: "addon",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "description",
                width: Some(
                    727,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "source",
                width: Some(
                    110,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "num_downloads",
                width: Some(
                    105,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "game_version",
                width: Some(
                    105,
                ),
                hidden: true,
            },
            ColumnConfigV2 {
                key: "date_released",
                width: Some(
                    105,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "install",
                width: Some(
                    85,
                ),
                hidden: false,
            },
        ],
        aura_columns: [
            ColumnConfigV2 {
                key: "title",
                width: None,
                hidden: false,
            },
            ColumnConfigV2 {
                key: "local",
                width: Some(
                    120,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "remote",
                width: Some(
                    120,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "author",
                width: Some(
                    85,
                ),
                hidden: false,
            },
            ColumnConfigV2 {
                key: "status",
                width: Some(
                    110,
                ),
                hidden: false,
            },
        ],
    },
    window_size: Some(
        (
            1905,
            851,
        ),
    ),
    scale: None,
    backup_directory: None,
    backup_addons: false,
    backup_wtf: false,
    hide_ignored_addons: false,
    self_update_channel: Stable,
    weak_auras_account: {
        Retail: "MAGLORE",
    },
    alternating_row_colors: true,
}
11:56:56.510 [ajour::gui][DEBUG] antialiasing: true
11:56:56.779 [ajour_core::utility][DEBUG] checking for application update
11:56:56.779 [ajour_core::theme][DEBUG] loading user themes
11:56:56.786 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
11:56:56.840 [ajour::gui::update][DEBUG] Message::CachesLoaded(error: false)
11:56:56.840 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
11:56:56.846 [ajour::gui::update][DEBUG] Message::Parse
11:56:56.846 [ajour::gui::update][DEBUG] preparing to parse addons in "D:\\World of Warcraft\\_retail_\\Interface/AddOns"
11:56:56.847 [ajour::gui::update][DEBUG] preparing to parse addons in "D:\\World of Warcraft\\_ptr_\\Interface/AddOns"
11:56:56.847 [ajour::gui::update][DEBUG] preparing to parse addons in "D:\\World of Warcraft\\_beta_\\Interface/AddOns"
11:56:56.847 [ajour::gui::update][DEBUG] preparing to parse addons in "D:\\World of Warcraft\\_classic_\\Interface/AddOns"
11:56:56.847 [ajour::gui::update][DEBUG] preparing to parse addons in "D:\\World of Warcraft\\_classic_ptr_\\Interface/AddOns"
11:56:56.847 [ajour_core::parse][DEBUG] Retail PTR - parsing addons folder
11:56:56.847 [ajour_core::parse][DEBUG] Retail - parsing addons folder
11:56:56.847 [ajour_core::parse][DEBUG] Classic PTR - parsing addons folder
11:56:56.847 [ajour_core::parse][DEBUG] Classic - parsing addons folder
11:56:56.847 [ajour_core::parse][DEBUG] Retail Beta - parsing addons folder
11:56:56.847 [ajour_core::parse][DEBUG] Retail - 53 folders in AddOns directory to parse
11:56:56.849 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail PTR, is_installed: false)
11:56:56.849 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail, is_installed: true)
11:56:56.849 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail Beta, is_installed: false)
11:56:56.849 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Classic, is_installed: false)
11:56:56.849 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Classic PTR, is_installed: false)
11:56:56.849 [ajour][ERROR] Failed to parse addons
11:56:56.849 [ajour][ERROR] caused by: Addon directory not found: "D:\\World of Warcraft\\_ptr_\\Interface/AddOns"
11:56:56.850 [ajour][ERROR] Failed to parse addons
11:56:56.850 [ajour][ERROR] caused by: Addon directory not found: "D:\\World of Warcraft\\_classic_ptr_\\Interface/AddOns"
11:56:56.850 [ajour::gui::update][DEBUG] Message::ListWeakAurasAccounts(Retail, num_accounts: 2)
11:56:56.850 [ajour][ERROR] Failed to parse addons
11:56:56.850 [ajour][ERROR] caused by: Addon directory not found: "D:\\World of Warcraft\\_classic_\\Interface/AddOns"
11:56:56.851 [ajour_core::parse][DEBUG] Retail - 53 fingerprints: 53 cached, 0 calculated, 0 added, 0 removed
11:56:56.851 [ajour][ERROR] Failed to parse addons
11:56:56.851 [ajour][ERROR] caused by: Addon directory not found: "D:\\World of Warcraft\\_beta_\\Interface/AddOns"
11:56:56.855 [ajour_core::parse][DEBUG] Retail - 52 addon folders successfully parsed from '.toc'
11:56:56.855 [ajour_core::parse][DEBUG] Retail - 0 valid cache entries retrieved
11:56:56.856 [ajour_core::parse][DEBUG] Retail - 52 unique fingerprints to check against curse api
11:56:57.106 [ajour::gui::update][DEBUG] Message::LatestRelease(Some("0.6.1"))
11:56:57.185 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 1)
11:56:57.384 [ajour_core::catalog][DEBUG] Successfully fetched and parsed https://github.com/casperstorm/ajour-catalog/releases/latest/download/tukui.json
11:56:57.643 [ajour_core::catalog][DEBUG] Successfully fetched and parsed https://github.com/casperstorm/ajour-catalog/releases/latest/download/wowi.json
11:56:58.225 [ajour_core::parse][DEBUG] Retail - 23 curse packages fetched
11:56:58.331 [ajour_core::parse][DEBUG] Retail - 2 tukui packages fetched
11:56:58.531 [ajour_core::parse][DEBUG] Retail - 5 wowi packages fetched
11:56:58.531 [ajour_core::parse][DEBUG] Retail - 0 git packages fetched
11:56:58.532 [ajour_core::parse][DEBUG] Retail - 23 addons built from curse packages
11:56:58.532 [ajour_core::parse][DEBUG] Retail - 1 addons built from tukui packages
11:56:58.532 [ajour_core::parse][DEBUG] Retail - 0 addons built from wowi packages
11:56:58.532 [ajour_core::parse][DEBUG] Retail - 0 addons built from git packages
11:56:58.532 [ajour_core::parse][DEBUG] Retail - 1 unknown addon folders
11:56:58.532 [ajour_core::parse][DEBUG] Retail - 25 addons successfully parsed
11:56:58.533 [ajour::gui::update][DEBUG] Message::ParsedAddons(Retail, 25 addons)
11:56:59.369 [ajour_core::catalog][DEBUG] Successfully fetched and parsed https://github.com/casperstorm/ajour-catalog/releases/latest/download/curse.json
11:56:59.415 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(15748 addons in catalog)
11:57:00.843 [ajour::gui::update][DEBUG] Interaction::ModeSelected(MyWeakAuras(Retail))
11:57:03.875 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
11:57:04.122 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 1)
11:57:05.865 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
11:57:06.112 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 3)
11:57:07.390 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
11:57:07.634 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 2)
11:57:07.985 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
11:57:08.136 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 0)
11:57:08.663 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
11:57:08.797 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 0)
11:57:09.865 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
11:57:10.038 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 2)
11:57:11.028 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
11:57:11.210 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 3)
11:57:13.316 [ajour::gui::update][DEBUG] Interaction::ModeSelected(About)
11:57:16.022 [ajour::gui::update][DEBUG] Interaction::OpenLink(https://getajour.com)
11:57:17.730 [ajour::gui::update][DEBUG] Interaction::ModeSelected(About)
11:58:04.743 [ajour::gui::update][DEBUG] Interaction::ModeSelected(MyWeakAuras(Retail))
11:58:09.078 [ajour::gui::update][DEBUG] Interaction::SortAuraColumn(Status, Asc)
11:58:09.956 [ajour::gui::update][DEBUG] Interaction::SortAuraColumn(Status, Desc)
12:03:12.527 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:03:12.806 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 3)
12:03:13.568 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:03:13.726 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 2)
12:03:16.027 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:03:16.177 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 0)
12:03:19.050 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:03:19.200 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 1)
12:03:21.871 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:03:22.064 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 3)
12:03:24.923 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:03:25.070 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 0)
12:03:27.126 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:03:27.298 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 3)
12:03:29.419 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:03:29.599 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 3)
12:03:31.355 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:03:31.522 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 2)
12:05:18.018 [ajour::gui::update][DEBUG] Interaction::ModeSelected(About)
12:05:23.785 [ajour::gui::update][DEBUG] Interaction::ModeSelected(About)
12:05:28.042 [ajour::gui::update][DEBUG] Interaction::ModeSelected(MyWeakAuras(Retail))
12:05:29.294 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:05:29.483 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 2)
12:05:30.492 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:05:30.650 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 1)
12:05:31.127 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:05:31.482 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 1)
12:05:32.024 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:05:32.172 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 0)
12:05:33.106 [ajour::gui::update][DEBUG] Interaction::Refresh(My WeakAuras)
12:05:33.290 [ajour::gui::update][DEBUG] Message::ParsedAuras(Retail, num_auras: 3)
12:06:46.593 [ajour::gui::update][DEBUG] Interaction::OpenLink(https://wago.io/Afenar_Mage/114)
```

**Comment by fraukas** [comment] 2021-01-04 17:28
This seems similar to issue #465 but with the list missing some auras.

**Comment by tarkah** [comment] 2021-01-04 18:04
Thanks for opening this bug report! I think I know whats going on here. There is no issue parsing your saved variables file for weak auras, hence no errors in the log. The reason for the inconsistency has to be due to the Wago.io API we query. I'd guess it's sometimes not returning results for your auras. We only show results that match against the Wago.io API.

I'll see if I can reproduce the inconsistency in the API call to confirm. 

@casperstorm Should we be showing ALL auras, regardless of if they match to Wago.io? This would fix this inconsistency problem likely due to their API, as well as custom auras not from Wago? We can maybe show a `-` in the remote column to indicate there was no API match?

**Comment by tarkah** [comment] 2021-01-04 18:09
And another thing I noticed, the reason `Holy&DC_AfenarUI` is never showing up is because we're not properly URL encoding that string, so the `&` sign is throwing things off in our API query.

**Comment by tarkah** [comment] 2021-01-04 18:20
@Maglore85 Can you submit the following in your browser and see if you consistently get 4 items to return? I always get the 4 items.

https://data.wago.io/api/check/weakauras?ids=Afenar_Warrior,Afenar_Mage,Afenar_Shadow,Holy%26DC_AfenarUI

**Comment by casperstorm** [comment] 2021-01-04 18:50
> @casperstorm Should we be showing ALL auras, regardless of if they match to Wago.io? This would fix this inconsistency problem likely due to their API, as well as custom auras not from Wago? We can maybe show a `-` in the remote column to indicate there was no API match?

We could do that then, however we should then consider:

- Introducing a `Source` so it's clear from a column which is Wago which is Offline/Personal/Local and which is, in the future, something else.
- Consider what happens when pressing on a non wago aura.

How does that sound?

**Comment by tarkah** [comment] 2021-01-04 18:53
Agreed, that'd make it consistent to how we show "Unknown" for source on the addon side. We can disable the clickable row for addons without a valid Wago.io source

**Comment by Maglore85** [comment] 2021-01-04 19:07
> 
> 
> @Maglore85 Can you submit the following in your browser and see if you consistently get 4 items to return? I always get the 4 items.
> 
> https://data.wago.io/api/check/weakauras?ids=Afenar_Warrior,Afenar_Mage,Afenar_Shadow,Holy%26DC_AfenarUI

Yes, I get this reply:

```[{"_id":"r1HtRGizG","name":"Afenar | Warrior | Shadowlands","slug":"Afenar_Warrior","url":"https://wago.io/Afenar_Warrior","created":"2017-12-23T00:08:29.080Z","modified":"2020-12-21T07:51:48.082Z","game":"sl","username":"Afenar","regionType":"group","version":113,"versionString":"3.4.6-113","changelog":{"text":"","format":"bbcode"}},{"_id":"H1T-NFUMG","name":"Afenar | Shadow | Shadowlands","slug":"Afenar_Shadow","url":"https://wago.io/Afenar_Shadow","created":"2017-12-19T12:20:20.740Z","modified":"2020-12-21T06:28:21.221Z","game":"sl","username":"Afenar","regionType":"group","version":156,"versionString":"3.4.2-156","changelog":{"text":"","format":"bbcode"}},{"_id":"HkC8t4YGz","name":"Afenar | Holy & Discipline | Shadowlands","slug":"Holy&DC_AfenarUI","url":"https://wago.io/Holy&DC_AfenarUI","created":"2017-12-21T13:38:30.298Z","modified":"2020-12-01T09:15:57.281Z","game":"sl","username":"Afenar","regionType":"group","version":41,"versionString":"3.3.1-41","changelog":{"text":"","format":"bbcode"}},{"_id":"S16Dtxiff","name":"Afenar | Mage | Shadowlands","slug":"Afenar_Mage","url":"https://wago.io/Afenar_Mage","created":"2017-12-22T21:30:12.745Z","modified":"2020-12-21T06:58:59.138Z","game":"sl","username":"Afenar","regionType":"group","version":114,"versionString":"3.4.4-114","changelog":{"text":"","format":"bbcode"}}]```

**Comment by tarkah** [comment] 2021-01-04 19:50
Ahh, so I don't think the API is giving us inconsistent results. I think it's all due to that percent encoding issue. If that slug `Holy&DC_AfenarUI` is the first parameter in the URL string, the whole request returns 0. If it's the last item, it'll return 3 results.

So the percent decoding fix should resolve this entire issue so we always get the above response of all 4 items.

**Comment by tarkah** [comment] 2021-01-04 21:44
@Maglore85 can you test the attached and confirm it works:

[ajour - wa fix 2020.01.04.zip](https://github.com/casperstorm/ajour/files/5766921/ajour.-.wa.fix.2020.01.04.zip)

**Comment by Maglore85** [comment] 2021-01-04 22:05
It is working with the exe supplied even after 15-20 manual refresh.
Now that's what I call efficacy...

Should I use that .exe or go back to the old one and update it when you release a new version ?

**Comment by tarkah** [comment] 2021-01-04 22:12
Awesome!

Go ahead and use that executable since it's now working for you. It's still marked as version 0.6.1, so when we roll out 0.6.2-rc.1 or 0.6.2, you'll still be presented with an update option and be back on master release.

**Comment by Maglore85** [comment] 2021-01-04 22:12
Excellent !

Thank you for the support :)

**Closed** 2021-01-04 23:48 UTC
Labels: B - bug
