### ISSUE TITLE
Close and Reopen again

### ISSUE THREAD

**Issue by RAtwood90** [casperstorm/ajour#383] opened 2020-11-22 15:11 UTC
Downloaded Ajour Today got my first Issue then i'am going to open it all was fine i maximized the Window and close it.

If i reopen it again it's moved to the right Corner and the Window Setting arent't saved.

**Comment by tarkah** [comment] 2020-11-23 16:58
duplicate of #269

**Closed by tarkah** 2020-11-23 16:58 UTC
