### ISSUE TITLE
Panic crash on start: Invalid glyph_hor_side_bearing [Arch Linux]

### ISSUE THREAD

**Issue by rockerBOO** [casperstorm/ajour#265] opened 2020-10-18 17:10 UTC
**Describe the bug**
ajour crashes on start. Using the compatibility suggestion I am getting a panic.

`12:49:22.662 [panic][ERROR] thread 'main' panicked at 'Invalid glyph_hor_side_bearing': /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/ab_glyph-0.2.5/src/ttfp.rs:263`

**To Reproduce**
1. cargo run --no-default-features --features opengl

**Expected behavior**
Expected it to boot. 

Maybe something related with `iced` git release being different.

**Software involved**
Please complete the following information:
 - OS: Arch
 - Ajour version: master (90481043387df23ac062e9b7aa9486f457cfc02f)
 - (if applicable) Addon name, flavor (classic or retail) and version:

**Additional context**
```
➜ cargo -V
cargo 1.47.0 (f3c7e066a 2020-08-28)
➜ rustc -V
rustc 1.47.0 (18bf6b4f0 2020-10-07)
➜ uname -r
5.8.14-arch1-1
```
**Log Output**
```
➜ cargo run --no-default-features --features opengl
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/ajour`
13:06:47.170 [ajour][INFO] Ajour 0.4.1 has started.
13:06:47.171 [ajour::gui][DEBUG] antialiasing: false
13:06:47.278 [ajour_core::config][DEBUG] loading config
13:06:47.278 [ajour_core::utility][DEBUG] checking for application update
13:06:47.278 [ajour_core::theme][DEBUG] loading user themes
13:06:47.279 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
13:06:48.813 [panic][ERROR] thread 'main' panicked at 'Invalid glyph_hor_side_bearing': /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/ab_glyph-0.2.5/src/ttfp.rs:263
   0: log_panics::init::{{closure}}
             at /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
   1: std::panicking::rust_panic_with_hook
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:573:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153:18
   4: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475:5
   5: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85:14
   6: core::option::expect_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213:5
   7: core::option::Option<T>::expect
             at /home/rockerboo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:333:21
   8: <ab_glyph::ttfp::FontVec as ab_glyph::font::Font>::h_side_bearing_unscaled
             at /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/ab_glyph-0.2.5/src/ttfp.rs:191:31
   9: <ab_glyph::font_arc::FontArc as ab_glyph::font::Font>::h_side_bearing_unscaled
             at /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/ab_glyph-0.2.5/src/font_arc.rs:106:9
  10: <&F as ab_glyph::font::Font>::h_side_bearing_unscaled
             at /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/ab_glyph-0.2.5/src/font.rs:209:9
  11: ab_glyph::scale::ScaleFont::h_side_bearing
             at /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/ab_glyph-0.2.5/src/scale.rs:153:33
  12: <glyph_brush::glyph_brush::GlyphBrush<V,X,F,H> as glyph_brush::glyph_calculator::GlyphCruncher<F,X>>::glyph_bounds_custom_layout::{{closure}}
             at /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/glyph_brush-0.7.0/src/glyph_brush.rs:130:33
  13: core::iter::traits::iterator::Iterator::fold
             at /home/rockerboo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2004:21
  14: <glyph_brush::glyph_brush::GlyphBrush<V,X,F,H> as glyph_brush::glyph_calculator::GlyphCruncher<F,X>>::glyph_bounds_custom_layout
             at /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/glyph_brush-0.7.0/src/glyph_brush.rs:122:9
  15: glyph_brush::glyph_calculator::GlyphCruncher::glyph_bounds
             at /home/rockerboo/.cargo/registry/src/github.com-1ecc6299db9ec823/glyph_brush-0.7.0/src/glyph_calculator.rs:106:9
  16: iced_glow::text::Pipeline::measure
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/glow/src/text.rs:100:13
  17: <iced_glow::backend::Backend as iced_graphics::backend::Text>::measure
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/glow/src/backend.rs:209:9
  18: iced_graphics::widget::text::<impl iced_native::widget::text::Renderer for iced_graphics::renderer::Renderer<B>>::measure
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/graphics/src/widget/text.rs:34:9
  19: <iced_native::widget::text::Text<Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/widget/text.rs:139:13
  20: iced_native::element::Element<Message,Renderer>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/element.rs:228:9
  21: <iced_native::widget::button::Button<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/widget/button.rs:169:27
  22: <iced_native::element::Map<A,B,Renderer> as iced_native::widget::Widget<B,Renderer>>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/element.rs:325:9
  23: iced_native::element::Element<Message,Renderer>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/element.rs:228:9
  24: iced_native::layout::flex::resolve
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/layout/flex.rs:99:26
  25: <iced_native::widget::row::Row<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/widget/row.rs:149:9
  26: iced_native::element::Element<Message,Renderer>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/element.rs:228:9
  27: iced_native::layout::flex::resolve
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/layout/flex.rs:99:26
  28: <iced_native::widget::row::Row<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/widget/row.rs:149:9
  29: iced_native::element::Element<Message,Renderer>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/element.rs:228:9
  30: iced_native::layout::flex::resolve
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/layout/flex.rs:99:26
  31: <iced_native::widget::column::Column<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/widget/column.rs:148:9
  32: iced_native::element::Element<Message,Renderer>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/element.rs:228:9
  33: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/widget/container.rs:160:27
  34: iced_native::element::Element<Message,Renderer>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/element.rs:228:9
  35: iced_native::layout::flex::resolve
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/layout/flex.rs:99:26
  36: <iced_native::widget::column::Column<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/widget/column.rs:148:9
  37: iced_native::element::Element<Message,Renderer>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/element.rs:228:9
  38: <iced_native::widget::container::Container<Message,Renderer> as iced_native::widget::Widget<Message,Renderer>>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/widget/container.rs:160:27
  39: iced_native::element::Element<Message,Renderer>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/element.rs:228:9
  40: <iced_graphics::renderer::Renderer<B> as iced_native::renderer::Renderer>::layout
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/graphics/src/renderer.rs:52:22
  41: iced_native::user_interface::UserInterface<Message,Renderer>::build
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/user_interface.rs:112:21
  42: iced_native::program::state::build_user_interface
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/program/state.rs:189:26
  43: iced_native::program::state::State<P>::new
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/native/src/program/state.rs:38:34
  44: iced_glutin::application::run
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/glutin/src/application.rs:91:21
  45: iced::application::Application::run
             at /home/rockerboo/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/fb015a8/src/application.rs:229:13
  46: ajour::gui::run
             at src/gui/mod.rs:661:5
  47: ajour::main
             at src/main.rs:63:13
  48: core::ops::function::FnOnce::call_once
             at /home/rockerboo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  49: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/rockerboo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18
  50: std::rt::lang_start::{{closure}}
             at /home/rockerboo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  51: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373:40
      std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337:19
      std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379:14
      std::rt::lang_start_internal
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51:25
  52: std::rt::lang_start
             at /home/rockerboo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  53: main
  54: __libc_start_main
  55: _start
```

**Comment by serlin** [comment] 2020-11-04 06:16
While not a prefect test, I was unable to reproduce on a Manjaro machine this evening. I was able to compile and run without panicking. 

```
➜  ~ uname -r
5.8.16-2-MANJARO
➜  ~ cargo -V
cargo 1.46.0
➜  ~ rustc -V
rustc 1.46.0
```

Happy to help debug if you have thoughts on differences to check.

**Comment by casperstorm** [comment] 2020-11-04 07:42
> While not a prefect test, I was unable to reproduce on a Manjaro machine this evening. I was able to compile and run without panicking.
> 
> ```
> ➜  ~ uname -r
> 5.8.16-2-MANJARO
> ➜  ~ cargo -V
> cargo 1.46.0
> ➜  ~ rustc -V
> rustc 1.46.0
> ```
> 
> Happy to help debug if you have thoughts on differences to check.

@serlin Thanks, I can run it on my Manjaro machine as well. To be sure you can try with `rustc 1.47.0` aswell.

**Comment by casperstorm** [comment] 2020-11-04 07:43
@rockerBOO are you able to compile and run any of `iced` examples:

https://github.com/hecrj/iced/tree/master/examples/tour

**Comment by rockerBOO** [comment] 2020-11-04 18:09
Panics with that example too. 

```
[2020-11-04T18:07:31Z ERROR gfx_memory::heaps] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 54673408, effective: 30074624 }, size: 8589934592 }
[2020-11-04T18:07:31Z ERROR gfx_memory::heaps] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 16777216, effective: 1280 }, size: 25206985728 }
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(256) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(2048) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(16384) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(4194304) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(25600) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(2600192) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(5600000) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(1400064) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(12800) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(240128) is
still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(60160) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(40192) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(36096) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(16777216) is still used
[2020-11-04T18:07:31Z ERROR gfx_memory::allocator::linear] Not all allocations from LinearAllocator were freed
[2020-11-04T18:07:31Z ERROR gfx_descriptor::allocator] DescriptorAllocator is dropped
```

[backtrace.log](https://github.com/casperstorm/ajour/files/5489708/backtrace.log)

**Comment by casperstorm** [comment] 2020-11-04 20:30
So a issue with upstream. Ill label it.

**Comment by casperstorm** [comment] 2020-12-22 20:27
See https://github.com/casperstorm/ajour/issues/453.
Will close this issue in favor of above.

**Closed by casperstorm** 2020-12-22 20:27 UTC
Labels: B - crash, OS - linux, S - iced

**Comment by rockerBOO** [comment] 2021-06-09 02:30
I ended up resolving this. Apparently my default fonts were not being supported (Inter and Public Sans). Once I removed these defaults from my `~/.config/fontconfig/fonts.conf` it is now working. Would be nice to be able to set a different font for ajour in the config though.

**Comment by casperstorm** [comment] 2021-06-09 06:37
Great to hear that @rockerBOO.
Yes, absolutly. I'll look into support your own fonts, and maybe also bundle a default ajour font along the program going forward.
