### ISSUE TITLE
Optional columns support for Catalog

### ISSUE THREAD

**Issue by Anthuang** [casperstorm/ajour#300] opened 2020-10-25 05:46 UTC
**Describe the bug**
The column option in the settings does not affect the columns in the catalog. This does work in the "My Addons" page. Not sure if the settings is meant to only change that page, or also the catalog.

**To Reproduce**
1. Go to "Catalog"
2. Click on "Settings"
3. See error

**Expected behavior**
Like the "My Addons" page, the catalog should also be changed by column option in the settings.

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.4.4

**Comment by casperstorm** [comment] 2020-10-25 14:50
It's technically not a bug, but we just dont have optional column support for Catalog just yet, however it will be included very soon!

**Closed** 2020-10-29 20:08 UTC
Labels: type: feature
